-- Chạy trong Supabase Dashboard → SQL Editor.
create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 10),
  score integer not null check (score >= 0),
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.scores enable row level security;

create index if not exists scores_score_created_idx
  on public.scores (score desc, created_at asc);

 drop policy if exists "public can read scores" on public.scores;
create policy "public can read scores"
  on public.scores for select
  using (true);

 drop policy if exists "authenticated users can submit scores" on public.scores;
create policy "authenticated users can submit scores"
  on public.scores for insert to authenticated
  with check (auth.uid() = user_id);
