-- Chạy trong Supabase Dashboard → SQL Editor.
create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 10),
  score integer not null check (score >= 0),
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- Migration an toàn nếu bảng scores đã tồn tại từ phiên bản Neon cũ.
alter table public.scores
  add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.scores
  add column if not exists created_at timestamptz not null default now();

alter table public.scores enable row level security;

create index if not exists scores_score_created_idx
  on public.scores (score desc, created_at asc);

 drop policy if exists "public can read scores" on public.scores;
create policy "public can read scores"
  on public.scores for select
  using (true);

 drop policy if exists "authenticated users can submit scores" on public.scores;
create policy "authenticated users can submit scores"
  on public.scores for insert to authenticated
  with check (
    auth.uid() = user_id
    and score between 0 and 100000
    and char_length(player_name) between 1 and 10
  );

-- Không cấp policy UPDATE/DELETE: điểm đã ghi không thể bị sửa hoặc xóa từ client.

-- Run ticket do Vercel Function tạo; client không được đọc hoặc sửa bảng này.
create table if not exists public.score_runs (
  run_id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  started_at timestamptz not null default now(),
  submitted_at timestamptz
);

alter table public.score_runs enable row level security;
-- Không tạo policy client cho score_runs; service_role của Vercel Function bypasses RLS.
create index if not exists score_runs_user_started_idx
  on public.score_runs (user_id, started_at desc);
