-- Supabase Dashboard -> SQL Editor -> chạy toàn bộ file này.
-- Database dùng Supabase PostgreSQL; auth.users là nguồn user UUID.
-- Client không truy cập trực tiếp; API server dùng SUPABASE_SERVICE_ROLE_KEY.

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  player_name text not null,
  score integer not null,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint scores_player_name_length check (char_length(btrim(player_name)) between 1 and 10),
  constraint scores_score_range check (score between 0 and 100000)
);

create table if not exists public.score_runs (
  run_id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  started_at timestamptz not null default now(),
  submitted_at timestamptz,
  constraint score_runs_submitted_after_start check (submitted_at is null or submitted_at >= started_at)
);

-- Leaderboard: ORDER BY score DESC, created_at ASC, id ASC.
create index if not exists scores_leaderboard_idx
  on public.scores (score desc, created_at asc, id asc);

-- Admin history and user run history.
create index if not exists scores_created_idx
  on public.scores (created_at desc);
create index if not exists scores_user_created_idx
  on public.scores (user_id, created_at desc);
create index if not exists score_runs_user_started_idx
  on public.score_runs (user_id, started_at desc);

-- Only open tickets are updated during score submission.
create index if not exists score_runs_open_idx
  on public.score_runs (run_id, user_id)
  where submitted_at is null;

-- Safe rerun support for databases created from an earlier schema version.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'scores_player_name_length') then
    alter table public.scores add constraint scores_player_name_length
      check (char_length(btrim(player_name)) between 1 and 10);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'scores_score_range') then
    alter table public.scores add constraint scores_score_range
      check (score between 0 and 100000);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'score_runs_submitted_after_start') then
    alter table public.score_runs add constraint score_runs_submitted_after_start
      check (submitted_at is null or submitted_at >= started_at);
  end if;
end $$;

alter table public.scores enable row level security;
alter table public.score_runs enable row level security;

-- Explicit deny for client roles. service_role bypasses RLS server-side.
revoke all on table public.scores from anon, authenticated;
revoke all on table public.score_runs from anon, authenticated;
