(function () {
  'use strict';

  var app = document.getElementById('app');
  if (!app) return;

  app.innerHTML = `
<div id="netDot"><i></i><span id="netTxt" data-i18n="connecting">đang kết nối…</span></div>
<div id="hud" class="hidden"><div id="score">0</div><div id="bestHud">kỷ lục · —</div><div id="combo" aria-live="polite"></div></div>
<div id="runTag" class="hidden"><span id="runNo">ván 01</span><span id="runKj">霧朝</span><span id="runVn">sương sớm</span></div>
<div id="evBanner"><span class="kanji" id="evKanji">風</span><div><b id="evName"></b><i id="evDesc"></i><div id="evBar"><i id="evBarI"></i></div></div></div>
<div id="hint" class="hidden"><svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 14l7-7 7 7"/></svg><span data-i18n="touchHint">chạm để vỗ cánh</span></div>
<div class="screen" id="titleScreen">
  <div class="panel home-panel">
    <div class="home-primary">
      <div class="kana">CHUYẾN BAY BẦU TRỜI</div><h1 data-i18n="title">SKY BIRD</h1><div class="rule"><i></i><b></b><i></i></div><p class="sub" data-i18n="subtitle">một chuyến bay qua trời hoa anh đào</p>
      <div class="hero-stats"><div class="hero-stat"><span class="stat-label" data-i18n="recordLabel">kỷ lục</span><span class="stat-value best" id="bestTitle" data-i18n="noRecord">chưa có</span></div><div class="hero-stat"><span class="stat-label" data-i18n="flightsLabel">ván đã bay</span><span class="stat-value best" id="runsTitle"></span></div><div class="hero-stat coin-stat"><span class="stat-label" data-i18n="walletLabel">ví coin</span><span class="stat-value" id="coinWallet" aria-live="polite"><b id="coinCount">0</b> <span data-i18n="coinsLabel">coin</span></span></div></div>

      <div class="selector"><div class="selLabel" data-i18n="sky">trời</div><div class="selGrid" id="mapGrid"></div></div>
      <div class="home-actions"><button class="btn solid" id="startBtn" data-i18n="start">bắt đầu bay</button><button class="btn ghost" id="lbBtn" data-i18n="leaderboard">bảng thiên hạ</button><button class="btn ghost" id="shopBtn" data-i18n="shop">cửa hàng</button><button class="btn ghost" id="settingsBtn" data-i18n="settings">cài đặt</button><button class="btn ghost" id="accountBtn" data-i18n="account">tài khoản</button></div>
    </div>
    <aside class="home-side">
      <section class="rules-card" aria-labelledby="rulesTitle"><div class="rail-kicker">luật bay / fair play</div><h3 id="rulesTitle">Bay sạch, bay xa</h3><ul class="rules-list"><li><span class="rule-icon" aria-hidden="true">01</span><span>Chạm hoặc nhấn Space để vỗ cánh; vượt mỗi cặp ống được cộng 1 điểm.</span></li><li><span class="rule-icon" aria-hidden="true">02</span><span>Thu coin trên đường bay; cuối ván nhận thêm <b>1 coin / 10 điểm</b>, chỉ tính một lần.</span></li><li><span class="rule-icon" aria-hidden="true">03</span><span>Mỗi ván chỉ có một lượt hồi sinh hợp lệ; điểm online được máy chủ kiểm tra.</span></li></ul><div class="protection-status" id="protectionStatus"><i aria-hidden="true"></i><span>lớp bảo vệ phiên đang hoạt động</span></div></section>
      <div class="keys"><kbd>SPACE</kbd>hoặc chạm màn hình</div><nav class="policy-links" aria-label="Thông tin website"><a href="game-guide.html">Hướng dẫn chơi</a><a href="privacy-policy.html">Privacy Policy</a><a href="terms-of-use.html">Terms of Use</a></nav>
    </aside>
  </div>
</div>
<div class="screen hidden feature-screen" id="accountScreen"><div class="panel feature-panel"><div class="kana">旅人</div><h2 data-i18n="account">TÀI KHOẢN</h2><p class="sub" id="accountStatus">chơi offline</p><div class="account-card"><div class="account-avatar" id="accountAvatar">?</div><div><strong id="accountEmail">Khách</strong><span id="accountPlan">chơi cục bộ</span></div></div><div class="account-stats"><div><span data-i18n="recordLabel">kỷ lục</span><b id="accountBest">0</b></div><div><span data-i18n="flightsLabel">ván đã bay</span><b id="accountRuns">0</b></div><div><span data-i18n="coinsLabel">coin</span><b id="accountCoins">0</b></div></div><div class="feature-actions"><button class="btn solid" id="accountLogin" data-i18n="login">đăng nhập</button><button class="btn ghost" id="accountRegister" data-i18n="signup">tạo tài khoản</button><button class="btn ghost hidden" id="accountLogout" data-i18n="logout">đăng xuất</button><button class="btn ghost" id="accountClose" data-i18n="close">đóng</button></div></div></div>
<div class="authModal hidden" id="authModal" role="dialog" aria-modal="true" aria-labelledby="authMode"><div class="authBox"><div class="kana">旅人</div><h2 id="authMode" data-i18n="login">ĐĂNG NHẬP</h2><p class="sub" id="authIntro">Đăng nhập để ghi danh bảng thiên hạ</p><label class="sr-only" for="authEmail">email</label><input id="authEmail" type="email" autocomplete="email" inputmode="email" required placeholder="email" data-i18n-placeholder="email"><label class="sr-only" for="authPassword">mật khẩu</label><input id="authPassword" type="password" autocomplete="current-password" minlength="8" required placeholder="mật khẩu (ít nhất 8 ký tự)" data-i18n-placeholder="password"><div class="authActions"><button class="btn solid" id="emailLogin" data-i18n="login">đăng nhập</button><button class="btn solid hidden" id="emailSignup" data-i18n="signup">tạo tài khoản</button><button class="btn ghost" id="authModeSwitch">tạo tài khoản mới</button><button class="btn ghost" id="authRecover">quên mật khẩu?</button><button class="btn ghost" id="googleLogin" data-i18n="google">Google</button><button class="btn ghost" id="authClose" data-i18n="close">đóng</button></div><div id="authMsg" aria-live="polite"></div></div></div>
<div class="screen hidden feature-screen" id="shopScreen"><div class="panel feature-panel shop-panel"><div class="kana">商店</div><div class="shop-heading"><div><h2 data-i18n="shop">CỬA HÀNG</h2><p class="sub" data-i18n="shopSubtitle">mở khóa chim bằng coin</p></div><div class="shop-wallet"><span data-i18n="walletLabel">ví coin</span><b id="shopCoinCount">0</b></div></div><div class="selGrid shop-grid" id="shopGrid"></div><div id="shopScreenMsg" class="shop-msg" aria-live="polite"></div><div class="feature-actions"><button class="btn ghost" id="shopClose" data-i18n="close">đóng</button></div></div></div>
<div id="settingsOverlay" role="dialog" aria-modal="true" aria-labelledby="settingsTitle"><div class="settingsCard"><div class="kana">設定</div><h2 id="settingsTitle" data-i18n="settings">CÀI ĐẶT</h2><label for="languageSelect" data-i18n="language">ngôn ngữ</label><select id="languageSelect" aria-label="language"><option value="vi">Tiếng Việt</option><option value="en">English</option><option value="ja">日本語</option></select><label for="volumeRange" data-i18n="volume">âm lượng</label><div class="volumeControl"><input id="volumeRange" type="range" min="0" max="100" step="1" value="50" aria-label="volume"><output id="volumeValue">50%</output></div><button class="btn ghost" id="muteToggle" type="button" data-i18n="mute">tắt âm thanh</button><div><button class="btn ghost" id="settingsClose" data-i18n="close">đóng</button></div></div></div>
<div class="screen hidden" id="lbScreen"><div class="panel feature-panel"><div class="kana">順位表</div><h2 data-i18n="leaderboard">BẢNG THIÊN HẠ</h2><p class="sub" data-i18n="topFlights">top 10 chuyến bay</p><div class="rule"><i></i><b></b><i></i></div><div class="lbWrap" id="fullLb"></div><div class="lbStatus" id="fullStatus"></div><div class="feature-actions"><button class="btn ghost" id="lbClose" data-i18n="close">đóng</button></div></div></div>
<div class="screen hidden" id="overScreen"><div class="panel"><div class="hanko" aria-hidden="true">終</div><div class="kana">旅の終わり</div><h2 data-i18n="complete">HOÀN TẤT</h2><div class="rows"><div class="row"><span data-i18n="score">điểm</span><span class="dots"></span><b id="finalScore">0</b></div><div class="row"><span data-i18n="record">kỷ lục</span><span class="dots"></span><b id="finalBest">0</b></div></div><div class="newbest hidden" id="newBest" data-i18n="newRecord">— kỷ lục mới —</div><div class="runLine" id="overRun"><span class="kj" id="overRunKj"></span><span id="overRunVn"></span></div><div class="nameRow" id="nameRow"><input id="nameInput" maxlength="10" placeholder="tên người bay" data-i18n-placeholder="namePlaceholder" autocomplete="off" spellcheck="false"><button class="btn solid small" id="sendBtn" data-i18n="submitScore">ghi danh</button></div><div class="lbWrap" id="miniLb"></div><div class="lbStatus" id="lbStatus"></div><div><button class="btn solid" id="retryBtn" data-i18n="retry">bay lại</button><br><button class="btn ghost" id="homeBtn" data-i18n="home">màn chính</button></div></div></div>
<button id="pauseBtn" aria-label="tạm dừng game">Ⅱ</button><div id="pauseOverlay"><div class="pauseCard"><div class="kana">休止</div><h2 data-i18n="pauseTitle"> TẠM DỪNG</h2><p data-i18n="pauseHint">Nhấn P hoặc nút tiếp tục để bay lại</p><button class="btn solid" id="resumeBtn" data-i18n="resume">tiếp tục</button></div></div><div id="reviveOverlay"><div class="reviveCard"><div class="kana">再生</div><h2 data-i18n="reviveTitle">HỒI SINH?</h2><p data-i18n="reviveHint">Xem quảng cáo hợp lệ để tiếp tục ván này một lần.</p><div id="reviveAdBox" data-i18n="adArea">khu vực quảng cáo</div><button class="btn solid" id="reviveAdBtn" data-i18n="watchAd">xem quảng cáo</button><button class="btn ghost" id="reviveSkip" data-i18n="endFlight">kết thúc ván</button><div id="reviveStatus"></div></div></div><div id="securityOverlay" role="alertdialog" aria-modal="true" aria-labelledby="securityTitle"><div class="securityCard"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3 4 6v5c0 5 3.4 8.4 8 10 4.6-1.6 8-5 8-10V6l-8-3z"/><path d="M12 8v4M12 16h.01"/></svg><h2 id="securityTitle">Phiên chơi đã bị khóa</h2><p id="securityMessage">Phát hiện môi trường không an toàn. Hãy đóng công cụ debug và tải lại trang.</p></div></div>
`;
})();
