import { readFileSync, writeFileSync } from 'node:fs';
import { strict as assert } from 'node:assert';

const html = readFileSync('index.html', 'utf8');
const adminHtml = readFileSync('admin.html', 'utf8');
const adminApi = readFileSync('api/admin-data.mjs', 'utf8');
const adminE2E = readFileSync('e2e/admin.e2e.mjs', 'utf8');
const scripts = [...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map((m) => m[1]);
const gameJs = readFileSync('game.js', 'utf8');
const source = `${html}\n${gameJs}`;
assert(source.includes('homeLeaderboard'));
assert(adminHtml.includes('id="appView"'), 'Admin dashboard markup missing');
assert(adminHtml.includes('/api/admin-data'), 'Admin API integration missing');
assert(adminHtml.includes('noindex,nofollow'), 'Admin page must not be indexed');
assert(adminApi.includes('requireAdmin'), 'Admin API must enforce server-side authorization');
assert(adminE2E.includes('ADMIN_E2E_BASE_URL'), 'Admin E2E must support a configurable Vercel URL');
assert(adminE2E.includes('meta[name="robots"]'), 'Admin E2E must check robots metadata');
assert(adminE2E.includes('/api/admin-data'), 'Admin E2E must check unauthenticated admin API access');
assert(source.includes('refreshHomeLeaderboard'));
assert(source.includes('signInWithOAuth'));
assert(source.includes('signInWithPassword'));
assert(source.includes('SUPABASE_REDIRECT_URL'));
assert(source.includes('setPaused'));
assert(source.includes("id:'aurora'"), 'Aurora map definition missing');
assert(readFileSync('e2e/game.e2e.mjs', 'utf8').includes("localStorage.getItem('chimse.map')) === 'aurora'"), 'Playwright new-map coverage missing');
assert(source.includes('pauseOverlay'));
assert(source.includes('HISTORY_KEY'));
assert(source.includes('PENDING_KEY'));
const backupFunction = source.match(/function backupPayload\(\)\{([\s\S]*?)\n/);
assert(backupFunction && !backupFunction[1].includes('pendingScores'), 'backup must not export online score queue');
assert(source.includes('schemaVersion:2'), 'backup schema must exclude online score queue');
assert(source.includes('savePendingScore'));
assert(source.includes('flushPending'));
assert(source.includes('schedulePendingRetry'));
assert(source.includes('exportBackup'));
assert(source.includes('importBackupFile'));
assert(source.includes('encryptBackup'));
assert(source.includes('AES-GCM'));
assert(source.includes('SKY_REWARDED_AD'));
assert(source.includes('sky-ad-blocked'));
assert(source.includes('adBlocked'));
assert(source.includes('blockedProvider'));
assert(source.includes('blocked-or-unavailable'));
assert(source.includes('LANG='));
assert(source.includes('detectLocale'));
const localeEntries = [...source.matchAll(/\['[a-z][a-z0-9-]*','[^']*'\]/g)];
assert(localeEntries.length >= 100, `Expected at least 100 locale entries, got ${localeEntries.length}`);
assert(source.includes("LANG.zh=Object.assign"), 'Chinese locale dictionary missing');
assert(source.includes("LANG.hi=Object.assign"), 'Hindi locale dictionary missing');
assert(source.includes('if(!LANG[code])LANG[code]=Object.assign({},LANG.en'), 'locale fallback missing');
assert(source.includes('settingsOverlay'));
assert(source.includes('property="og:image"'));
assert(source.includes('property="og:image:width"'));
assert(source.includes('property="og:image:height"'));
assert(source.includes('twitter:card" content="summary_large_image"'));
assert(source.includes('twitter:image'));
assert(source.includes('"@type":"VideoGame"'));
assert(readFileSync('og-image.png').length > 1000, 'OG thumbnail asset missing');
assert(readFileSync('scripts/generate-config.mjs', 'utf8').includes('PUBLIC_SITE_URL'), 'Dynamic SEO URL build missing');
const jaLocale = source.match(/ja:\{([\s\S]*?)\}\};/);
assert(jaLocale, 'Japanese locale dictionary missing');
const i18nKeys = [...source.matchAll(/data-i18n="([^"]+)"/g)].map((m) => m[1]);
for (const key of new Set(i18nKeys)) assert(jaLocale[1].includes(`${key}:`), `Japanese translation missing: ${key}`);
for (const key of ['title','subtitle','touchHint','authTitle','pauseTitle','reviveTitle','namePlaceholder','email','password','signup','google','apply','dismiss']) assert(jaLocale[1].includes(`${key}:`), `Japanese translation missing: ${key}`);
assert(source.includes('schemaVersion:1'));
assert(readFileSync('neon/schema.sql', 'utf8').includes('create table if not exists public.scores'));
assert(readFileSync('neon/schema.sql', 'utf8').includes('create table if not exists public.score_runs'));
assert(readFileSync('.env.example', 'utf8').includes('DATABASE_URL='));
assert(readFileSync('.env.example', 'utf8').includes('SUPABASE_URL='));
const vercel = readFileSync('vercel.json', 'utf8');
assert(readFileSync('api/locale.mjs', 'utf8').includes('x-vercel-ip-country'));
assert(readFileSync('docs/vercel-supabase-google-oauth.md', 'utf8').includes('SUPABASE_SERVICE_ROLE_KEY'));
assert(vercel.includes('Content-Security-Policy'));
assert(vercel.includes('X-Frame-Options'));
const security = readFileSync('api/_security.mjs', 'utf8');
const runTicketApi = readFileSync('api/run-ticket.mjs', 'utf8');
const submitApi = readFileSync('api/submit-score.mjs', 'utf8');
assert(security.includes('SUPABASE_SERVICE_ROLE_KEY'));
assert(security.includes('DATABASE_URL'));
assert(security.includes('isAdminUser'));
assert(security.includes('ADMIN_EMAILS'));
assert(security.includes('ADMIN_USER_IDS'));
assert(security.includes('timingSafeEqual'));
assert(runTicketApi.includes('authenticate'));
assert(submitApi.includes('verifyRunTicket'));
assert(submitApi.includes('too_many_submissions'));
assert(submitApi.includes('score_rate_exceeded'));
assert(readFileSync('scripts/test-flows.mjs', 'utf8').includes('backup AES-GCM'));
assert(readFileSync('e2e/game.e2e.mjs', 'utf8').includes('option[value="zh"]'), 'Playwright Chinese locale coverage missing');
assert(readFileSync('e2e/game.e2e.mjs', 'utf8').includes('Incomplete rewarded ad must not revive'), 'Playwright rewarded rejection coverage missing');
assert(readFileSync('e2e/game.e2e.mjs', 'utf8').includes('Leaderboard payload score was not validated'), 'Playwright Leaderboard payload coverage missing');
writeFileSync('/tmp/sky-source-current.js', source, 'utf8');
console.log(`verified HTML + game.js; ${scripts.length} inline metadata script block(s)`);
