import { readFileSync, writeFileSync } from 'node:fs';
import { strict as assert } from 'node:assert';

const html = readFileSync('index.html', 'utf8');
const scripts = [...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map((m) => m[1]);
assert(html.includes('homeLeaderboard'));
assert(html.includes('refreshHomeLeaderboard'));
assert(html.includes('signInWithOAuth'));
assert(html.includes('signInWithPassword'));
assert(html.includes('SUPABASE_REDIRECT_URL'));
assert(html.includes('setPaused'));
assert(html.includes('pauseOverlay'));
assert(html.includes('HISTORY_KEY'));
assert(html.includes('PENDING_KEY'));
assert(html.includes('savePendingScore'));
assert(html.includes('flushPending'));
assert(html.includes('schedulePendingRetry'));
assert(html.includes('exportBackup'));
assert(html.includes('importBackupFile'));
assert(html.includes('encryptBackup'));
assert(html.includes('AES-GCM'));
assert(html.includes('SKY_REWARDED_AD'));
assert(html.includes('LANG='));
assert(html.includes('detectLocale'));
assert(html.includes('settingsOverlay'));
assert(html.includes('schemaVersion:1'));
assert(!html.toLowerCase().includes('neon'));
assert(readFileSync('supabase/schema.sql', 'utf8').includes('authenticated users can submit scores'));
assert(readFileSync('.env.example', 'utf8').includes('SUPABASE_URL='));
const vercel = readFileSync('vercel.json', 'utf8');
assert(readFileSync('api/locale.mjs', 'utf8').includes('x-vercel-ip-country'));
assert(readFileSync('docs/vercel-supabase-google-oauth.md', 'utf8').includes('SUPABASE_SERVICE_ROLE_KEY'));
assert(vercel.includes('Content-Security-Policy'));
assert(vercel.includes('X-Frame-Options'));
const security = readFileSync('api/_security.mjs', 'utf8');
const runTicketApi = readFileSync('api/run-ticket.mjs', 'utf8');
const submitApi = readFileSync('api/submit-score.mjs', 'utf8');
assert(security.includes('SUPABASE_SERVICE_ROLE_KEY'));
assert(security.includes('timingSafeEqual'));
assert(runTicketApi.includes('authenticate'));
assert(submitApi.includes('verifyRunTicket'));
assert(submitApi.includes('too_many_submissions'));
assert(submitApi.includes('score_rate_exceeded'));
assert(readFileSync('scripts/test-flows.mjs', 'utf8').includes('backup AES-GCM'));
writeFileSync('/tmp/sky-inline-current.js', scripts.join('\n'), 'utf8');
console.log(`verified HTML and ${scripts.length} inline script blocks`);
