-- Chạy trong Neon SQL Editor hoặc Neon Console.
-- Supabase Auth vẫn cung cấp user UUID; Neon lưu user_id như dữ liệu server-side.
create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 10),
  score integer not null check (score between 0 and 100000),
  user_id uuid,
  created_at timestamptz not null default now()
);

alter table public.scores
  add column if not exists user_id uuid;
alter table public.scores
  add column if not exists created_at timestamptz not null default now();

create index if not exists scores_score_created_idx
  on public.scores (score desc, created_at asc);

create table if not exists public.score_runs (
  run_id uuid primary key,
  user_id uuid not null,
  started_at timestamptz not null default now(),
  submitted_at timestamptz
);

alter table public.score_runs
  add column if not exists user_id uuid;
alter table public.score_runs
  add column if not exists started_at timestamptz not null default now();
alter table public.score_runs
  add column if not exists submitted_at timestamptz;

create index if not exists score_runs_user_started_idx
  on public.score_runs (user_id, started_at desc);

create index if not exists score_runs_open_idx
  on public.score_runs (run_id, user_id)
  where submitted_at is null;

-- Không cấp quyền client trực tiếp; mọi truy vấn đi qua Vercel Function.
